### ISSUE TITLE
Disable Ivy throw error in prod mode

### ISSUE THREAD

**Issue by moein-shafiei** [tonysamperi/ngx-mat-timepicker#1]
When I add this 

```
"angularCompilerOptions": {
    "enableIvy": false
  }
```

to tsconfig.app.json I causes me error to build in prod mode

Directive NgxMatTimepickerDirective, Expected 1 arguments, but got 0.

**Comment by tonysamperi** [comment]
Hi @moein-shafiei can you provide a reproduction of the error e.g. in stackblitz (there's the option for IVI in the settings in case you don't know)?

**Comment by tonysamperi** [comment]
@moein-shafiei found it. A missing param on a @HostListener...the original mantainer wasn't a good developer...
Update to 9.0.5 and it's solved!
