### ISSUE TITLE
[BUG] - Unable to pass string type value when input time value in input field

### ISSUE THREAD

**Issue by LohWH** [tonysamperi/ngx-mat-timepicker#10]
**Describe the bug**
The time value that input manually instead of choosing from timepicker dialog will pass the time value as object but not string
![MicrosoftTeams-image (15)](https://user-images.githubusercontent.com/75016586/115170491-5cd6a500-a0f3-11eb-8bbb-16290e9cc762.png)
which will hit the TypeError: time.split is not a function
![image](https://user-images.githubusercontent.com/75016586/115171419-93adba80-a0f5-11eb-98c9-8b961ee8a549.png)

**To Reproduce**
remove the readonly in html input and type the time value in input field.

**Expected behavior**
A string type time value should be able to pass to the ngx-mat-timepicker.js 

**Desktop (if execution):**
 - OS: [Windows 10]
 - Browser [chrome]

** Versions
 - ngx-mat-timepicker version [11.0.5]
 - @angular/core version [11.2.4]
 - @angular/material version [11.2.3]
 - typescript version [4.0.3]

**Comment by tonysamperi** [comment]
If you're using the mat-timepicker directive the time needs to be selected from the picker.
You can use the "editable dial" option.

**Comment by tonysamperi** [comment]
By the way you can use a validator to format the input as an object
