### ISSUE TITLE
[BUG] - Internationalization does not work

### ISSUE THREAD

**Issue by Azel-ytof** [tonysamperi/ngx-mat-timepicker#103]
**Describe the bug**
Hi, I've configured internationalization like documentation, but one text stay in english.
I've do in app.module this : `NgxMatTimepickerModule.setLocale('fr-FR')` (in the imports array)

**Expected behavior**
The text `use arrows (⇅) to change the time` should adapt to selected language.

**Screenshots**
![image](https://github.com/tonysamperi/ngx-mat-timepicker/assets/50252147/4aeaea8d-6032-4cb4-a0b9-841ae74e2d57)

** Versions
 - ngx-mat-timepicker version : ^16.1.2
 - @angular/core version : ^16.0.0
 - @angular/material version : ^16.2.9
 - typescript version : ~5.0.2

**Additional context**
Sorry if you think it is not a bug.
In that case, could you tell me how to update this text ?

**Comment by tonysamperi** [comment]
It's not that I "think" it's not a bug. It's not a bug. Cause internationalization is for the clock, not for the texts...

What we can do is making that text dynamic...I need to look at the code...

I'll let you know...

**Comment by tonysamperi** [comment]
You can use the `@input` `editableHintTmpl` to change the template.
