### ISSUE TITLE
[Feature?] - Dots between minutes would be cool

### ISSUE THREAD

**Issue by angelaki** [tonysamperi/ngx-mat-timepicker#104]
First of all: I acutally really feel bad to abuse the Bug-Report for a Feature-Request - but how to contact you? At least it isn't for an Angular-Version-Update ... 

Right now I'm using the (discontinued) angular-material-picker (https://github.com/IliaIdakiev/angular-material-timepicker). This one showed some dots between the minutes that (imho) looked pretty great:

![image](https://github.com/tonysamperi/ngx-mat-timepicker/assets/38611461/46c3b76e-001b-410b-9afa-11edd6a80e7b)

Have you even tought about implementing these, too? Or would a PR be welcome containing it?

BR

Tristan

**Comment by tonysamperi** [comment]
ahahah "At least it isn't for an Angular version update" 😂😂😂

You know? It's not bad! 

If you want to go with a PR to help me, then probably I'll need to pick up, because I'm too finnicky...

But I think this can be thrown in as an option...

**Comment by tonysamperi** [comment]
Done in beta 17.1.0-beta.0 I will publish in the future, if nothing weird comes out of it!

Cheers

**Comment by angelaki** [comment]
Woohoo! I'm excited already! Thank you so much! :)

**Comment by tonysamperi** [comment]
@angelaki let me know when you try it!

**Comment by angelaki** [comment]
Sure I'll let you know! And thank you very much in advance! 👍 Will probably take some time since I need to swap my whole project from the deprecated picker to yours. And there'll sure be some caveats ...

**Comment by tonysamperi** [comment]
@angelaki sure, take your time...
