### ISSUE TITLE
Time dial not correctly stylized

### ISSUE THREAD

**Issue by kc7bfi** [tonysamperi/ngx-mat-timepicker#105]
When I display the time picker, the time dial is not correctly displayed; see the attached screenshots. If I add the following to my styles.scss, it helps but is still not perfect:

```
.mat-mdc-mini-fab {
  background-color: rgba(0,0,0,0)!important;
  color: black!important;
}
```

Am I doing something wrong?

**Desktop (if execution):**
 - OS: Windows 10
 - Browser: Chrome

** Versions
 - ngx-mat-timepicker version 17.0.3
 - @angular/core version 17.2.2
 - @angular/material version 17.2.1
 - typescript version 5.3.3

** Screenshots
![timepicker-1](https://github.com/tonysamperi/ngx-mat-timepicker/assets/3237084/eeea254b-0abe-427f-9d9b-3d094f40684d)
![timepicker-2](https://github.com/tonysamperi/ngx-mat-timepicker/assets/3237084/15dd00bf-cdb8-412e-bae6-d178f7e713e7)

**Comment by derekkite** [comment]
I'm seeing the same thing

**Comment by kc7bfi** [comment]
Adding the following to my main scss file fixed the issue:

```
:root {
  --mdc-fab-small-container-color: rgba(0,0,0,0);
}
```

**Comment by tonysamperi** [comment]
Yes, you're all doing something wrong...

https://tonysamperi.github.io/ngx-mat-timepicker/

As you can see in the demo side, the picker is just fine.

If you can setup a blitz reproducing the error, I can take a look.

**Comment by derekkite** [comment]
[https://stackblitz.com/edit/q4m6sg?file=src%2Fexample%2Fdatepicker-overview-example.html](url)

This worked with 17.0.0. Something changed in 17.2.

**Comment by derekkite** [comment]
> Adding the following to my main scss file fixed the issue:
> 
> ```
> :root {
>   --mdc-fab-small-container-color: rgba(0,0,0,0);
> }
> ```

This worked for me.

**Comment by tonysamperi** [comment]
Found it. They changed a css variable, that I couldn't see cause of yarn.lock.

Once I installed fresh dependencies I got the issue...whoever did that...what a twat!

**Comment by tonysamperi** [comment]
It's fixed, but I want to check #106 as well before publishing...we get two birds with one stone...
Keep you posted.

**Comment by MatthiasvB** [comment]
I installed in v17.1.0 but still have the same issue

**Comment by tonysamperi** [comment]
@MatthiasvB nope this time it's you. Just take the blitz linked above and update ngx-mat-lib to 17.1.0 and you'll see that the problem is gone.
And there was no point in opening a new issue having this one already.
