### ISSUE TITLE
Daylight Savings Time

### ISSUE THREAD

**Issue by harleenarora** [tonysamperi/ngx-mat-timepicker#107]
Starting today (from what I've noticed) selecting any time (2:00 PM for example) results in the time picker selecting one hour ahead (3:00 PM based on example).

I am in EST (-5). Today Daylight Savings Time changed over.

I have reproduced in my software and on the demo site.

**Comment by tonysamperi** [comment]
Hey @harleenarora 
why the dupe? Is this different from #106 ?
