### ISSUE TITLE
[BUG] - ngx-mat-timepicker-field throws error when using min Input

### ISSUE THREAD

**Issue by devAnky** [tonysamperi/ngx-mat-timepicker#108]
**Describe the bug**
When using the min option of the ngx-mat-timepicker-field and passing a DateTime and then using the arrows in the ui to change the time to a time less than the given min time an error occurs in the console:

> core.mjs:7494 ERROR TypeError: Cannot read properties of undefined (reading 'time')
>     at _NgxMatTimepickerControlComponent._setAvailableTime (ngx-mat-timepicker.mjs:3636:52)

When using the icon to open the picker, the hours less than the given min time will be disabled as expected. So it seems that only the behaviour of the fields does not work correctly.

**To Reproduce**
[stackblitz reproducing the bug](https://stackblitz.com/~/github.com/devAnky/ngx-mat-timepicker-min-bug)
The min time is set to now minus an hour, so use the arrows in the fields to select a time less than that and check the console logs.

**Expected behavior**
It should be prevented to use the arrows to select a time less than the given min input and no error should be displayed in the console log.

**Screenshots**
![image](https://github.com/tonysamperi/ngx-mat-timepicker/assets/26707880/4331d066-dcf4-4154-abdf-4c62d5584d17)

**Desktop (if execution):**
 - OS: Windows 11
 - Browser: Chrome
 
**Versions**
 - ngx-mat-timepicker version [17.0.3]
 - @angular/core version [17.2.0]
 - @angular/material version [17.2.2]
 - typescript version [5.3.2]

**Locale**
- Europe/Berlin

**Comment by tonysamperi** [comment]
Ah this was nice!
This was born when I optimized the code for a certain callback that only made sense if you had `format=12`.
But I forgot to run the callback at least once, when you have `format=24`!
Weird that no one noticed this before!
Excellent timing by the way, I'm just publishing a new release!

**Comment by tonysamperi** [comment]
Fixed in v17.1.0
