### ISSUE TITLE
[BUG] - Doesn't Show Clock Popup Well on Small Screens

### ISSUE THREAD

**Issue by CatGuardian** [tonysamperi/ngx-mat-timepicker#11]
**Describe the bug**
On a small screen (anything at 340 pixels wide or less) the clock face popup acquires a scroll bar and doesn't display properly. As this is a really good control to use on mobile devices, I would expect that the clock popup dialog would just stretch further out on the screen rather than have a maximum width and then get a scroll bar. I would expect that at the least this control would look nice on an iPhone 5 which has a pixel width of 320px. It looks like the control would naturely work on a device of 300px if the max-width limitation was removed. I don't expect it to work on anything less than 300px but I would think it should handle 320px at a minimum and I would suggest targeting 300px and larger to work.

The problem is caused by the element:
```
<div id="cdk-overlay-0" class="cdk-overlay-pane ngx-mat-timepicker-dialog" style="max-width: 80vw;position: static;">
```

See how it is setting the max-width to 80vw? That is causing the problem. If you just get rid of that then you can see it fixes the issue.

I don't know how you want to handle it but maybe adding the max-width as an input parameter to the main component directives?

**To Reproduce**
Use Google Chrome's "device toolbar" in the developer tools window and switch to other device views, like the iPhone 5. I would also recommend setting it to response and go through all of the pixels to watch what happens. You will notice that there are 2 points when the clock popup gets a scrollbar: anything at or less than 340px as well as between 381 pixels and 360 pixels wide. So go to the demo site https://tonysamperi.github.io/ngx-mat-timepicker/ and play with the device size emulator thing in google chrome to see what is going on.

**Expected behavior**
See the description of the bug. The expected behaviors is outlined there.

**Screenshots**
![image](https://user-images.githubusercontent.com/7755283/118199469-d4f56980-b418-11eb-8ae6-3b5db208135f.png)

**Other Info**
See this link for a potential work around / description of the general problem with the cdk-overlay https://www.gitmemory.com/issue/angular/components/9823/528824405

**Comment by CatGuardian** [comment]
Workaround to resolve this for now:

Add the following to your application's global styles file:

```
// Fixes bug where the timepicker clock popup doesn't look right on small screens.
.cdk-overlay-pane.ngx-mat-timepicker-dialog {
  max-width: 100%;
}
```

**Comment by tonysamperi** [comment]
The max width of the overlay is an angular/material component, so changing its style is not the right approach.
I will check if the size of the clock-face can be adjusted when going below a threshold, for instance 360px.
I must also say that I was already aware of the situation, but I guess there aren't many devices with that resolution anymore...
Honestly I would wait for more complaints before taking any action...

**Comment by CatGuardian** [comment]
Hi @tonysamperi,

Thanks for getting back to me!    :)

Yeah I realize that it is an angular/material problem.

I didn't look into it but that link I added at the end in the other info section talks about being able to set the max-width on the dialog open call. But I didn't verify that is/still is a thing:

```
const d = this.dialog.open(DialogXXXXXComponent, {
  width: 'calc(100% - 50px)',
  maxWidth: '100vw'
});
```
https://www.gitmemory.com/issue/angular/components/9823/528824405


As for the rule you proposed as a work around, I tried that and it doesn't work. The `max-width: 80vw` is set on the culprit element's style itself: `<div id="cdk-overlay-0" class="cdk-overlay-pane ngx-mat-timepicker-dialog" style="max-width: 80vw;position: static;">`

**Comment by tonysamperi** [comment]
I was thinking about this today...
There's no way to provide dynamically a value through an InjectionToken.
The value should come from a service or something...
OR (and I think this may be a better approach) we could add a method to update the locale, overriding the default config.
Would this solve your issue?

**Comment by tonysamperi** [comment]
Closing this as css workarounds are possible and no further complaints arrived.
