### ISSUE TITLE
Feature Request: Support Horizontal Orientation of Mobile Devices

### ISSUE THREAD

**Issue by CatGuardian** [tonysamperi/ngx-mat-timepicker#12]
Hello,

I would like to put in for a feature request. It would be nice if the time picker popup dialog would play nice with horizontal orientations of the mobile devices.

I don't really have a suggestion on what to do to accomplish this. One idea might be: when the height is less than 406px to not use the Material dialog's action buttons and instead implement your own buttons off to the right of the clock. But only if the device is horizontal orientation (height less than 406px).

I was thinking trying to target to make it look good at a height of 290px or greater.

Here is a picture of my Pixel 2 in horizontal mode:

![image](https://user-images.githubusercontent.com/7755283/118330781-7a6a1500-b4cd-11eb-8a58-b3883a7ac3c2.png)

**Comment by tonysamperi** [comment]
Sorry, I can't handle feature requests. I maintain the library in my spare time, so I can't afford developing extra stuff.

**Comment by CatGuardian** [comment]
I can appreciate that. Thank you for the response!   :)

For those who stumble upon this, here is the workaround:

Add this to the global styles file.

```
// Fixes issue where the timepicker clock popup doesn't look right on small screens in the vertical position.
.cdk-overlay-pane.ngx-mat-timepicker-dialog {
  max-width: 100% !important;
}

// Fixes issue where the timepicker clock popup doesn't look right on small screens in the horizontal position
@media (max-height: 415px) {
  .ngx-mat-timepicker-dialog {

    .timepicker__main-content {
      transform: scale(.7,.7) translate(0px, -45px);
      height: 178px;
    }

    .timepicker-header {
      height: 42px;
    }
    ngx-mat-timepicker-dial {
      transform: scale(.7,.7);
    }

    .mat-dialog-actions {
      min-height: 36px;
      height: 36px;
    }

  }
}
```

Result on my Pixel 2:

![image](https://user-images.githubusercontent.com/7755283/118335423-41ce3980-b4d5-11eb-88a8-664b4faf5ada.png)
