### ISSUE TITLE
[BUG] - Outdated version of RXJS used

### ISSUE THREAD

**Issue by deefactorial** [tonysamperi/ngx-mat-timepicker#121]
**NOTE**

**REQUESTS WILL BE IMMEDIATELY DELETED, you cannot do feature requests such as "Update to Angular xx"**
I deal with updates with my own schedule, don't need a reminder. 

**Describe the bug**

When I run the build I get the following error:

```
./node_modules/ngx-mat-timepicker/fesm2022/ngx-mat-timepicker.mjs:4321:36-47 - Error: export 'takeUntil' (imported as 'takeUntil$1') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)
```

**To Reproduce**
Possibly create a stackblitz reproducing the bug, or a zip with basic sources for a reproduction

OR

1. `yarn add ngx-mat-timepicker@^17.0.3`
2. `yarn start`

**Expected behavior**
The build to succeed without error

**Screenshots**

**Desktop (if execution):**
 - OS: [e.g. iOS] ubuntu linux
 - Browser [e.g. chrome, safari] chrome

** Versions
 - ngx-mat-timepicker version [e.g. 9.0.0] 17.0.3
 - @angular/core version [e.g. 10.2.3] 17.3.12
 - @angular/material version [e.g. 10.2.7] 17.3.10
 - typescript version [es. 3.9.2] 5.4.5
 - rxjs version ^6.6.7

**Additional context (optional)**

Looks like product was build using an older version of RXJS and needs to be upgraded to newer version of rxjs
https://stackoverflow.com/questions/51128911/error-ts2339-property-takeuntil-does-not-exist-on-type-observablefoo-and

**Comment by tonysamperi** [comment]
You really think that would be possible?
