### ISSUE TITLE
[BUG] - null value causes runtime error

### ISSUE THREAD

**Issue by DevinloperNL** [tonysamperi/ngx-mat-timepicker#14]
**Describe the bug**
In my scenario, an API sends back a `null` value. This causes a runtime error in the library.

**To Reproduce**
Assign a `null` value to the timepicker input.

**Expected behavior**
The library should be able to accept a `null` value as an empty value without throwing a runtime error.

**Screenshots**
![image](https://user-images.githubusercontent.com/22426652/121324943-7cc75f80-c911-11eb-87b0-859f91e66ea3.png)
![image](https://user-images.githubusercontent.com/22426652/121325141-a5e7f000-c911-11eb-810a-7553409a3e97.png)

**Desktop (if execution):**
 - OS: [MacOS Big Sur]
 - Browser [Brave (Chromium)]

**Versions**
 - ngx-mat-timepicker version [10.0.3]
 - @angular/core version [10.2.5]
 - @angular/material version [10.2.7]
 - tslib version [2.0.0]

**Comment by tonysamperi** [comment]
@DevinloperNL  What's the value from your service when it's not null?

**Comment by DevinloperNL** [comment]
See the `callTime1` value below the highlighted value in my screenshot

**Comment by tonysamperi** [comment]
Even `callTime1` is not a valid value. Please check how the formControl works when you don't use it programmatically to learn how to use it programmatically.

**Comment by DevinloperNL** [comment]
> Even `callTime1` is not a valid value. Please check how the formControl works when you don't use it programmatically to learn how to use it programmatically.

This value works correctly for me, debugging this shows that the runtime error occurs only at the `null` value.

**Comment by DevinloperNL** [comment]
> > Even `callTime1` is not a valid value. Please check how the formControl works when you don't use it programmatically to learn how to use it programmatically.
> 
> This value works correctly for me, debugging this shows that the runtime error occurs only at the `null` value.

Your own documentation even says that the `callTime1` value should be valid:
`Set a default value and time for a timepicker. The format of the time is in 12 hours notation 11:00 PM or in **24 hours notation 23:00**. A Date string won't work.`

**Comment by tonysamperi** [comment]
I'm telling you that you're not working correctly.
