### ISSUE TITLE
[BUG] - Mannual change of the input attached to the time picker results in error

### ISSUE THREAD

**Issue by georgeene** [tonysamperi/ngx-mat-timepicker#17]
**Describe the bug**
If the input attached to the time picker componet is mannualy changed the NgxMatTimepickerDirective.UpdateValue fails with error. This also prevents the [(ngModel)] to work properly (or formControl ). 

**To Reproduce**
Reproducable with the code in the demo: remove readonly="true"  and add [disableClick]="true"  (for convinience).
Changing the value in the input (mannually with out the picker) will trigger the described error.

**Expected behavior**
No error to happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/5549016/128836232-3cd74e4a-84e6-49d7-b07d-04a518fa3e13.png)

** Versions
 - ngx-mat-timepicker version 12.0.0
 - @angular/core version [e.g. 12.0.0]
 
Extra context:
The value recieved by the directive is an event and not a string in the form "11:00"

**Comment by georgeene** [comment]
Just found https://github.com/tonysamperi/ngx-mat-timepicker/issues/10.  I will use the editable dial.

**Comment by tonysamperi** [comment]
@georgeene also keep in mind that you can type manually, but you need to adjust your formControl to format the value of the field as 

```
{ time: "12:00" }
```
So you would probably need to create a custom form control (see https://material.angular.io/guide/creating-a-custom-form-field-control).
The "problem" is that you would need to validate that input (a custom validator in the custom form control is enough), but if you're fine with that, it should work.

Bests
