### ISSUE TITLE
Setting locale dynamically

### ISSUE THREAD

**Issue by elliotritchie** [tonysamperi/ngx-mat-timepicker#2]
I'm trying to set the locale dynamically in my module:

```
{
  provide: NGX_MAT_TIMEPICKER_LOCALE,
  useExisting: LOCALE_ID
}
```

I'm getting the following error though:

```
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'ngx-mat-timepicker/lib/tokens/ngx-mat-timepicker-time-locale.token'
```

https://stackblitz.com/edit/angular-m9pxhu?file=src%2Fapp%2Fapp.module.ts

Could `NGX_MAT_TIMEPICKER_LOCALE` be included in the package's exports to allow this to be supported or alternatively default to use `LOCALE_ID` instead of `en-US`?

Thanks!

**Comment by tonysamperi** [comment]
@elliotritchie I don't see the point of exposing the NGX_MAT_TIME_PICKER locale. It's a provider for internal use.
Just follow the docs and you should be able to pass the LOCALE_ID instead of en-US

This way:

```
@NgModule({
  imports: [NgxMatTimepickerModule.setLocale(LOCALE_ID)]
})
export class AppModule {}
```

**Comment by elliotritchie** [comment]
The locale for my app is loaded asynchronously, it will eventually also be able to be changed by the user. I don't think `NgxMatTimepickerModule.setLocale` supports this?

```
providers: [
  {
    provide: APP_INITIALIZER,
    deps: [ConfigurationService],
    useFactory: (s: ConfigurationService) => () => s.loadConfiguration().toPromise(),
    multi: true
  },
  {
    provide: Configuration,
    deps: [ConfigurationService],
    useFactory: (s: ConfigurationService) => s.configuration
  }
  {
    provide: LOCALE_ID,
    deps: [Configuration],
    useFactory: (c: Configuration) => c.localeId
  },
  {
    provide: NGX_MAT_TIMEPICKER_LOCALE,
    useExisting: LOCALE_ID
  }
]
```

**Comment by tonysamperi** [comment]
Unfortunately at this time you would be able to set the locale from your APP_INITIALIZER, but you wouldn't be able to change it afterwards...
I guess I could expose the NGX_MAT_TIMEPICKER_LOCALE and make a few changes to the main module accordingly...
If you know what I mean and want to try a pull request, we could speed up the change...
