### ISSUE TITLE
disabled state for ngx-mat-timepicker component ?

### ISSUE THREAD

**Issue by balajibadly** [tonysamperi/ngx-mat-timepicker#20]
`<mat-form-field class="fuse-mat-dense" floatLabel="always">
              <input matInput [ngxMatTimepicker]="startTime" formControlName="startTime" (blur)="onTouched()"
                placeholder="9:00 AM" />
              <mat-icon matSuffix (click)="startTime.open()">
                watch_later
              </mat-icon>
            </mat-form-field>
            <ngx-mat-timepicker [isEsc]="true" #startTime
              [disable]="(operatingHoursForm.get('mon').get('isClosed').value === true)"></ngx-mat-timepicker>
`

I can't disable this component, but I can disable FormControl.

even though the popup is opened when I clicked the icon.

**Comment by tonysamperi** [comment]
It has absolutely no sense to disable the component. 
If the input is disabled you should prevent it from opening the picker dialog.

**Comment by tonysamperi** [comment]
Also no feature requests are accepted so this post will be deleted.
