### ISSUE TITLE
Error: unable to resolve dependency tree

### ISSUE THREAD

**Issue by GitAttila** [tonysamperi/ngx-mat-timepicker#21]
Needs an update to Angular v13.
Could not resolve dependency: peer @angular/animations@"^12.0.5" from ngx-mat-timepicker@12.1.0
As a workaround, it can be installed with --legacy-peer-deps. flag for now.

**Comment by tonysamperi** [comment]
What exactly don't you understand about not accepting feature requests?
This post will be deleted.
The update will come when I have time to upgrade and test.
