### ISSUE TITLE
Update to Angular 13

### ISSUE THREAD

**Issue by Mathilde-Frere** [tonysamperi/ngx-mat-timepicker#22]
Hi Tony !

Thanks a lot for this time picker !
Could you update your project to Angular 13, please ?

I have tried to fork it and update it by myself but I have been blocked by the update of one of your custom dependencies ("smp-core-utils"). This module use Angular common 12.0.5 and I have no access to it.

Thanks

**Comment by tonysamperi** [comment]
Hi Mathilde,

yes that module is private so I'm the only one who can update...
As promised in the Readme I handle the updates as soon as possible.
I'm well aware that Angular 13 is out, but I need some time to upgrade everything...
I'm having a few free days around December 8th...You can expect the update to be out by then!

Cheers

**Comment by Mathilde-Frere** [comment]
Thanks for quickly answer me.

Of course I understand.
Take yout time.

Cheers

**Comment by tonysamperi** [comment]
Hi @Mathilde-Frere,

I'm sorry it took so long, but I'm about to publish v13.
I just updated that package "smp-core-utils"

So be ready :)

**Comment by tonysamperi** [comment]
Done! 🎉

**Comment by Mathilde-Frere** [comment]
Hi @tonysamperi,

No problem.
Very good news ! Thanks a lot for your work.

**Comment by cnbebop** [comment]
Thank you
