### ISSUE TITLE
[BUG] - Can't compile Angular 13 project because of smp-core-utils

### ISSUE THREAD

**Issue by alex-zar** [tonysamperi/ngx-mat-timepicker#23]
**Describe the bug**
The angular build is failing showing this error:

`./node_modules/smp-core-utils/fesm2020/smp-core-utils.mjs:203:16-21 - Error: export 'first' (imported as 'first') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrameScheduler, asapScheduler, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queueScheduler, race, range, scheduled, throwError, timer, using, zip)`

**To Reproduce**
Just added ngx-mat-timepicker to the project and trying to build and test

**Expected behavior**
Build should be successful out of the box

** Versions
 - ngx-mat-timepicker version - 13.0.0
 - @angular/core version - 13.1.2
 - @angular/material version - 13.1.2
 - typescript version - 4.5.4

**Comment by tonysamperi** [comment]
Check your rxjs version.
And I think you cant use Typescript 4.5.
You must stick with 4.4.x

**Comment by alex-zar** [comment]
Sorry for reopening this but I just wanted to say - thank you!
Yeah, by some reason rxjs was 6.5 and I was pretty sure Angular updated it (I recently had a migration from Angular 9 to Angular 13, step by step, version by version). Looks like I just lost a track of these versions.

Updating to rxjs 7.5.2 fixed the version. Btw, I didn't touch Typescript version yet.

Thanks again for the help and for the component!

**Comment by tonysamperi** [comment]
@alex-zar yep you're right...I remembered reading "Typescript@4.4" in the 13.0 release but they added 4.5 in 13.1! 
Cheers!
