### ISSUE TITLE
[BUG] - Toggle Button Icon is not at the button center

### ISSUE THREAD

**Issue by Johanneslueke** [tonysamperi/ngx-mat-timepicker#26]
**Describe the bug**

When using the \<ngx-mat-timepicker-field\> the toggle icon is not at the center of the toggle button. 
In the Image you can roughly see that the icon is not centered. the top of the icon touches the green line. 

**To Reproduce**
simply using: 

`
<ngx-mat-timepicker-field [defaultTime]="'11:11 AM'"></ngx-mat-timepicker-field>
`
or [stackblitz](https://stackblitz.com/edit/angular-plknjw)
**Expected behavior**
The green line should intersect the icon in the middle. If that is the case the icon is centered!

**Screenshots**
![image](https://user-images.githubusercontent.com/3592317/153416159-017274bd-6af5-4836-b3ce-4883353ccb57.png)
![image](https://user-images.githubusercontent.com/3592317/153427451-0b22ae55-119c-4e8a-bb5a-3a1fc12d4429.png)

**Desktop (if execution):**
 - OS: Linux Mint
 - Browser: Chrome

** Versions
 - ngx-mat-timepicker version [ ^13.0.0]
 - "material-design-icons": "^3.0.1",
 - @angular/core version ^13.2.2
 - @angular/material version [^13.2.2]
 - typescript version [^4.5.5]

**Comment by tonysamperi** [comment]
As you can see in the demo the button is centered.
So it's a problem with your style.

![image](https://user-images.githubusercontent.com/5957244/153427941-abc2a880-d860-4de1-bdde-936f0c0c3840.png)

**Comment by tonysamperi** [comment]
I don't know mate, I don't know what you used, I should inspect your site...the blitz isn't working also...
