### ISSUE TITLE
[BUG] - Summary of the problem here

### ISSUE THREAD

**Issue by mahen23** [tonysamperi/ngx-mat-timepicker#27]
**Describe the bug**
Picker appears with a transparent background. 

**Screenshots**
https://imgur.com/nyzAFAj

**Desktop (if execution):**
 - OS: LINUX
 - Browser [chrome]

** Versions
 - ngx-mat-timepicker version 12.0.0 / 12.1.0
 - @angular/core version 12.2.15
 - @angular/material version  12.2.13
 - typescript version 4.3.5

Followed the documentation, imported indigo-ping.css theme as required, still nothing

**Comment by tonysamperi** [comment]
It's quite obvious that you skipped some other step...
Sorry but you can't open issues for your misconfigurations.
You can try to get help using stackoverflow.com

**Comment by mahen23** [comment]
My bad, there was some CSS changes on our side that was breaking it: 

```
.ngx-mat-timepicker-dialog .mat-dialog-container {
  background: white !important;
  box-shadow: initial !important;
  overflow: auto !important;
}

```

**Comment by tonysamperi** [comment]
@mahen23 terrible fix! `!important` is never the answer!
