### ISSUE TITLE
Question - license: smp core utils

### ISSUE THREAD

**Issue by Johanneslueke** [tonysamperi/ngx-mat-timepicker#28]
Hello,  I've got a question regarding one of the dependcies you are using. The smp-core-utils 

What licence does this project have? The picker it self seems to be MIT.  But your dependcy, which you seems to be the author as well, is not clear. 

Could you shed some light regarding the licensing issue?

**Comment by tonysamperi** [comment]
Hi,

smp-core-utils is freely usable, but simply it's not open source.

Hope this helps.

T.
