### ISSUE TITLE
Feature request: Show time picker control in place instead of modal

### ISSUE THREAD

**Issue by mfrieling** [tonysamperi/ngx-mat-timepicker#3]
I'm currently working on an Ionic application (for desktop and tablet use) which mainly will be used outdoor and has an input assistance service helping the user will data inputs of all kinds by providing default values and reducing the amount of typing needed. This input assistance should be displayed consistently over all types of data (text fields, select lists, date inputs, time inputs, ...) in an aside window (I'm using the Material SideNav component for this).

The https://tiaguinho.github.io/material-community-components/timer-picker can be used directly without a popover or other kind of modal but is lacking some needed features which this one has. I.e. it is limited to 5 minutes steps and steps cannot be configured (e. g. 1 minute or 15 minutes). Those features are supported by this component, though.

So my request is a component which provides the UI to embed at the place where it is used in the markup. Basically it should contain everything inside the `<div mat-dialog-content></div>` of `ngx-mat-timepicker-dialog` plus related styles and logic.

**Comment by tonysamperi** [comment]
Sorry mate, but this would defeat the purpose of this library. We're talking about a totally different library, which requires a fairly complex UX and UI study. 
It has more sense that the other one fixes the inability to select single minutes...

**Comment by tonysamperi** [comment]
I'm closing this, for now, I'll keep this in mind for a future project.

**Comment by tonysamperi** [comment]
@mfrieling  I just remembered that you can achieve what you need by using "appendToInput".
That way the timepicker doesn't render in a dialog!
