### ISSUE TITLE
Update peer dependencies in `projects/ngx-mat-timepicker/package.json`

### ISSUE THREAD

**Issue by Juulsgaard** [tonysamperi/ngx-mat-timepicker#32]
**Describe the bug**
The peer dependencies for the exported package still points to an old version of Angular

**Expected behavior**
Peer dependencies should match the updated dependencies of the project and point to Angular 14

**Screenshots**

**Versions**
 - ngx-mat-timepicker version 14.0.0
 
 
 I don't know if you prefer issues or PRs for this type of change, but thought I would point out that the peer dependencies need to be updated.
 No hurry, and thank you for your service keeping this project up to date 👍

**Comment by joyson-madtha0** [comment]
I am facing the same issue.

Could not resolve dependency:
npm ERR! peer @angular/animations@"^13.0.3" from ngx-mat-timepicker@14.0.0
npm ERR! node_modules/ngx-mat-timepicker
npm ERR!   ngx-mat-timepicker@"^14.0.0" from the root project

**Comment by tonysamperi** [comment]
@Juulsgaard yes in this case a PR would have been nice 😁
It's fixed now.
