### ISSUE TITLE
 error TS2314: Generic type 'ɵɵPipeDeclaration' requires 2 type argument(s).

### ISSUE THREAD

**Issue by daniyaniazi** [tonysamperi/ngx-mat-timepicker#33]
I have followed the docs and simply trying to render a component but its not working as expected

**Comment by tonysamperi** [comment]
Not enough data to investigate, but since the demo site works without any error, you have some issue with your code.
If you can provide a Blitz I can take a look.

Cheers.

**Comment by daniyaniazi** [comment]
![image](https://user-images.githubusercontent.com/55786784/174803088-706e2553-7162-4975-ba0c-d48ee7e3e557.png)

please guide about the above errors @tonysamperi
