### ISSUE TITLE
[BUG] - NullInjectorError: No provider for NgxMatTimepickerLocaleService

### ISSUE THREAD

**Issue by devsaran** [tonysamperi/ngx-mat-timepicker#34]
**Describe the bug**
We are getting following error on runtime.

`NullInjectorError: R3InjectorError(ZoneModule)[NgxMatTimepickerLocaleService -> NgxMatTimepickerLocaleService -> NgxMatTimepickerLocaleService -> NgxMatTimepickerLocaleService]: 
  NullInjectorError: No provider for NgxMatTimepickerLocaleService!`

**Screenshots**

![Screenshot 2022-06-22 at 11 37 01 AM](https://user-images.githubusercontent.com/1410590/174955525-0e34ce92-5131-4cad-8683-4ee40267fe2b.png)

**Desktop (if execution):**
 - OS: MacOS
 - Browser: Chrome

** Versions
 - ngx-mat-timepicker version - 14.0.1
 - @angular/core version - 14.0.2
 - @angular/material version - 14.0.2
 - typescript version - 4.7.4

**Comment by tonysamperi** [comment]
Can't reproduce this, as the demo site is the latest version and doesn't have errors.
Please create a Blitz to reproduce.

**Comment by tonysamperi** [comment]
@devsaran with v 13.2.0 calling `NgxMatTimepickerModule.setLocale()` accidentally became mandatory.
I fixed in v 14.0.2.
