### ISSUE TITLE
[BUG] - Local cannot be set in standalone components

### ISSUE THREAD

**Issue by runner78** [tonysamperi/ngx-mat-timepicker#37]
**Describe the bug**
When I try to use the picker in a standalone component, I am unable to set the locale, i got the error:

`Type 'ModuleWithProviders<NgxMatTimepickerModule>' is not assignable to type 'any[] | Type<any>`

![Bildschirmfoto 2022-08-25 um 11 25 46](https://user-images.githubusercontent.com/7888460/186628460-48e2650f-2d03-4aa3-9bdd-5c3b37976d7a.png)

** Versions
 - ngx-mat-timepicker version [14.0.2]
 - @angular/core version [14.1.3]
 - @angular/material version [14.1.3]
 - typescript version [4.7.2]

**Comment by tonysamperi** [comment]
You should check Angular documentation because it doesn't work like that.
Plus you can use the service to change the locale afterwards.
