### ISSUE TITLE
Angular 11 support

### ISSUE THREAD

**Issue by duyuxuan** [tonysamperi/ngx-mat-timepicker#4]
When will the version for Angular 11 be released? @tonysamperi

**Comment by tonysamperi** [comment]
Hi, I think we'll have it by the end of the month / starting of March...

**Comment by tonysamperi** [comment]
I'll keep this open and close when I publish the update!

**Comment by duyuxuan** [comment]
@tonysamperi 
thank you.

**Comment by duyuxuan** [comment]
@tonysamperi 
I am so sorry for post message again.
I have been waiting for updates.
I will be very happy If you can update today.
or I have to use this component in the next Angular project.
Thanks for your contribution.

**Comment by tonysamperi** [comment]
@duyuxuan sorry mate but I won't be able to update today.
As I said, I can't guarantee the release date...

**Comment by duyuxuan** [comment]
@tonysamperi 
Thank you for your reply.
It is ok.
Looking forward to using it in the future.

**Comment by tonysamperi** [comment]
@duyuxuan today is the day! About to release 😁

**Comment by tonysamperi** [comment]
Done! Enjoy!
