### ISSUE TITLE
support seconds

### ISSUE THREAD

**Issue by hanoyn08** [tonysamperi/ngx-mat-timepicker#40]
Does it support seconds?

**Comment by bsallevi** [comment]
I also have this need to have the seconds

**Comment by tonysamperi** [comment]
Nope. At this time it doesn't support seconds. It could be extended and I think it shouldn't be much trouble. But certainly it's not fast.
I've had in mind to upgrade everything according to the material docs with date and everything (and time of course), but work has been keeping me busy lately.
Cheers
