### ISSUE TITLE
[BUG] - Timepicker toggle is styled differently than official Google datepicker toggle

### ISSUE THREAD

**Issue by aahventures** [tonysamperi/ngx-mat-timepicker#41]
**Describe the bug**
The design of the timepicker toggle, although seems analogous to how Google has designed their official [datepicker toggle](https://material.angular.io/components/datepicker/api#MatDatepickerToggle), does not look the same, especially when used side-by-side.

I understand a workaround is to create our own `matSuffix` element, but based on the fact that the timepicker toggle is a public component and that the component is mostly similar to the datepicker toggle, I assume they would be able to be used the same way.

**To Reproduce**
See https://stackblitz.com/edit/ngx-mat-timepicker-rzjnxj?file=src/app/app.component.html

**Expected behavior**
The toggle to be similar (in size and behavior) to the official Material datepicker toggle. Specifically for behavior that the ripple would be much smaller than what is used for a `mat-mini-fab`.

**Desktop (if execution):**
 - OS: MacOS
 - Chrome and safari

**Versions**
 - ngx-mat-timepicker version ^13.0.0
 - @angular/core version 13.3.7
 - @angular/material version 13.3.7
 - typescript version 4.6.4

**Additional context (optional)**
If needed, I can make a pull request. However, I don't think it'll be very backwards compatible look-wise.

**Comment by tonysamperi** [comment]
Well I think you're actually right. This is an heritage of the original library.
I don't know why the guy used a mat-mini-fab to do the toggle!
The right thing to do was using a mat-icon-button.
I'll definitely fix this in all the versions of the library (11, 12, 13 and 14).

**Comment by aahventures** [comment]
Awesome! Thanks for the quick response. Agree that `mat-icon-button` is probably the right choice. Also I think you could make the fixes much quicker than I, since you understand the lib much better than I do. However, if you would like I can attempt a PR.

**Comment by tonysamperi** [comment]
Fixed in both v13 and v14...I'll see if it's worth a fix in V12...there's a certain number of downloads...
I'll think about it in the next few days...
Cheers!
