### ISSUE TITLE
[BUG] - error with min set when changing value with keyboard arrow below the min

### ISSUE THREAD

**Issue by spectrosdennoce** [tonysamperi/ngx-mat-timepicker#48]
**NOTE**

**Describe the bug**
minimal value create error on consol when set the value below with the arrow and you can go below with the arrow

**To Reproduce**

1 define min on timepicker
2 go under the min with the arrow

**Expected behavior**
lock on min from the arrow and don't set error on console

**Screenshots**
![image](https://user-images.githubusercontent.com/59066535/204007857-93000a75-18f2-49d9-83fb-17209b36f5a5.png)
![image](https://user-images.githubusercontent.com/59066535/204007948-c00a523f-40b3-4dd2-a32a-6f8d211fd832.png)

**Desktop (if execution):**
 - Browser chrome

** Versions
 - ngx-mat-timepicker@^14.0.5

**Comment by tonysamperi** [comment]
I can't seem to reproduce this. Can you prepare a Blitz please?
