### ISSUE TITLE
[BUG] - "InvalidDateTime" when keyboard input enabled

### ISSUE THREAD

**Issue by cjohnston-nuvalence** [tonysamperi/ngx-mat-timepicker#49]
**Describe the bug**
When keyboard input is enabled, it is possible to easily trigger a "InvalidDateTime" error in the input area

**To Reproduce**
1. See https://github.com/cjohnston-nuvalence/ngx-mat-timepicker-keyboard (I couldn't figure out how to get it hooked up to Stackblitz) or simply set `[enableKeyboardInput]="true"` on a time picker.
2. Click in the input field to open the picker
3. In the minutes input, click at the left of the input so the cursor is before the digits
4. Start entering numbers
5. Any number >= 1 will immediately trigger the `InvalidDateTime` error
6. Any number of 0s may be entered, but the first non-zero number will trigger the `InvalidDateTime` error

**Expected behavior**
No error when editing values via keyboard. 

**Screenshots**
![2023-01-16_08-41-29 (1)](https://user-images.githubusercontent.com/116018261/212717612-2044ab89-8de4-4dae-87a6-06eb1e59be34.gif)

**Desktop (if execution):**
 - OS: [MacOS, Windows, iOS]
 - Browser [chrome, safari]

** Versions
 - ngx-mat-timepicker version 15.1.2
 - @angular/core version 15.1.0
 - @angular/material version 15.1.0
 - typescript version 4.9.4

**Comment by tonysamperi** [comment]
Sorry pal, but there must be something wrong with your code...
I tried on V14 and V15 and it works just fine.

Cheers

**Comment by cjohnston-nuvalence** [comment]
My example is an out of the box install of Angular 15 with Material and your module. There is no "my code" in this case. If you clone the repo and run it you should see the issue. Put the cursor before the digits and start typing...

**Comment by tonysamperi** [comment]
Ok I was able to reproduce.
Anywayy I agree that it could be handled better, but I don't see why you put the cursor at the beginning.
Just leave the cursor at the end and you will be able to type your numbers without any errors.
Otherwise if you put the cursor on the left, you simply delete before typing.
I'll keep this in mind and try to prevent the "Invalid" to be triggered, but I think it's an edge case...very edge...

**Comment by tonysamperi** [comment]
Fixed in v 15.1.4 @cjohnston-nuvalence
