### ISSUE TITLE
[BUG] Chrome 110 issue with ts-luxon (and luxon apparently)

### ISSUE THREAD

**Issue by riiight** [tonysamperi/ngx-mat-timepicker#51]
I don't know when this happened, but the picker has just stopped working. It looks like it may be related to the Chrome browser as it still works for me in Firefox and Edge. The version of Chrome that I am using is the latest version (Version 110.0.5481.78 (Official Build) (64-bit)). It seems to still be working in Firefox and Edge.

You can even see this on the demo (https://tonysamperi.github.io/ngx-mat-timepicker/). Just try picking any time under "Picker with 12h format". It will say "Invalid DateTime".

NOTE: This is also happening with https://agranom.github.io/ngx-material-timepicker/ which I believe this project was forked from?

**Comment by tonysamperi** [comment]
Just to align everybody, it's not the lib itself, but the DateTime wrapper underneath which is `ts-luxon`.
By the way yes, I started from agranom, but I did a heavy refactor of basically everything, just kept a few logics here and there, but there's not much of the original anymore.

Anyway. We were saying `ts-luxon`. I'll have to run some tests to see what happens. I still have Chrome 109, probably I'll get the update as we speak.

**Comment by jbuehlz** [comment]
Installing Brave LTS is fastest way to duplicate the error. Thanks @tonysamperi

**Comment by tonysamperi** [comment]
@jbuehlz nope, I'm not installing Brave. The issue is in Chrome and I can try everything I can to fix the issue on Chrome. 
For Brave I don't guarantee.

**Comment by tonysamperi** [comment]
Ok it's fixed...it seems that with the new update they changed a space in the meridiem with a non-breaking-space...
unbelievable...

**Comment by ashishpCACTUS** [comment]
@tonysamperi  - The issue has started with Chromium base update which has now replicated to all the Chromium based browsers - Chrome, Edge, Brave. So a fix on one should suffice and fix all other. Awaiting for the fix as now Firefox is the only alternative available as Chromium browsers have started giving error.

**Comment by gokulag731** [comment]
We are also facing the same issue. Awaiting for the fix.

**Comment by shreyanshjain16051992** [comment]
I am also facing same issue, please fix.

**Comment by tonysamperi** [comment]
@ashishpCACTUS good to know.
The fix is not simple at all, yesterday I thought I found a workaround on this side, but I'll have to fix on ts-luxon.
Btw I was able to reproduce the issue in luxon as well. 
As I said yesterday the problem is the way the 12h string is created by the browser (nbsp instead of space) which causes ts-luxon parser to fail...
I guess the fix is as simple as improving the tokens regex...
I'll keep you posted. 
Please avoid 328903813 comments saying "same issue here" everybody having chrome >= 110 has the issue.
Thanks.

**Comment by tonysamperi** [comment]
Being worked here => https://github.com/tonysamperi/ts-luxon/issues/4

Releasing fix in a few moments!

**Comment by pranavpandey86** [comment]
@tonysamperi  is this version v15.1.3 compatible with Angular14? I am getting errors that some peer dependency needs version 15.
