### ISSUE TITLE
[BUG] Chrome 110 issue with ts-luxon v2.x

### ISSUE THREAD

**Issue by alexyyzzz** [tonysamperi/ngx-mat-timepicker#53]
It works fine on 24h format. It does not work in Chrome only. Please refer to the error stated

<img width="725" alt="image" src="https://user-images.githubusercontent.com/82381876/218673331-152e67d4-c036-41be-8c8e-d261e8cc5b49.png">

 - Browser: chromium derived

** Versions
 - ngx-mat-timepicker version: 9.x
 - @angular/core version: not relevant
 - @angular/material version: not relevant
 - typescript version: not relevant
 - ts-luxon version: 2.0.3

**Comment by sathishra-Kore** [comment]
Facing the same issue, It is happening for the latest version of the chrome browser(110).

**Comment by tonysamperi** [comment]
Yeah, this has been fixed for recent versions of ts-luxon...I'll have to fix for older ones as well...
Working on it as soon as I can!

**Comment by alexyyzzz** [comment]
> 

Thanks @tonysamperi apologies for this as it is my first time posting an issue.

**Comment by tonysamperi** [comment]
Fixed in v9.1.3

**Comment by trixzter** [comment]
> Fixed in v9.1.3

can you also put a fix for version 10.x of the library? thanks

**Comment by tonysamperi** [comment]
@trixzter yup...working immediately as I have a few minutes...

**Comment by tonysamperi** [comment]
@trixzter done, published v 10.0.4

**Comment by trixzter** [comment]
> @trixzter done, published v 10.0.4

thanks, I'm currently testing the updated fix, what is the default format of the time picker output?

**Comment by trixzter** [comment]
my custom validation fails to validate the output string, I just noticed that there is a `U+202f` unicode character in the output format right after the minutes `h:mm a`, I'm using brave browser but the problem does not exist in safari,

**Comment by trixzter** [comment]
@tonysamperi everything is working now, I updated and relaunched my browser, thank you again for the immediate response about the problem
