### ISSUE TITLE
[BUG] - Showing Invalid dateTime after selecting the time with 12H format.

### ISSUE THREAD

**Issue by sathishra-Kore** [tonysamperi/ngx-mat-timepicker#54]
Showing Invalid dateTime after selecting the time with 12H format.

It is happening for latest browser version chrome(110)

can you give a fix ASAP

**Comment by bah99** [comment]
Oh ok, Thank you. 

I'm using edge chromium 
![image](https://user-images.githubusercontent.com/31727552/218752923-52668477-70da-4653-a7cf-4255012f08e5.png)

after testing on chrome it works perfectly.

Thanks

**Comment by kevinsar** [comment]
shoot updating chrome did work for me but now I have to figure out how to tell clients that... anyone have a code workaround we can use so we can fix it for everyone instead of telling clients to update their browser?

**Comment by tonysamperi** [comment]
USE THE SEARCH

**Comment by tonysamperi** [comment]
@sathishra-Kore use the template for issues and compile all the required fields
