### ISSUE TITLE
[BUG] - Getting Invalid DateTime on Microsoft Edge

### ISSUE THREAD

**Issue by sidsaxena0** [tonysamperi/ngx-mat-timepicker#55]
**Describe the bug**
Whenever I set some predefined time to my form such as 08:00 PM or 20:00 but instead it always displays InvalidDateTime in input. Also, upon selection of the time it should give a valid time string such 08:00 PM or 20:00 but it gives InvalidDateTime. I have verified my code and it works fine on all other browser, error only comes on Microsoft Edge (Version 110.0.1587.41 (Official build) (64-bit).
It wasn't the issue with earlier version just popped up few days back.

**To Reproduce**
1. Use time picker on any web page.
2. Bind it with ngModel or form.
3. Set any time but result will be invalidDateTime

**Expected behavior**
Whenever I set a time to my form such as 08:00 PM or 20:00. I expect input box to show this time but instead it always display InvalidDateTime in input. Also upon selection of the time it should give a valid time string such 08:00 PM or 20:00 but it gives InvalidDateTime.

**Screenshots**
![date](https://user-images.githubusercontent.com/10049774/219021612-22db3867-8080-4868-a043-cfb8e2bfdc96.jpg)

**Desktop (if execution):**
 - OS: Mac, Windows
 - Browser: Microsoft Edge

** Versions
 - ngx-mat-timepicker version [15.1.3]
 - @angular/core version [15.1.4]
 - @angular/material version [15.1.4]
 - typescript version [4.9.5]

**Comment by tonysamperi** [comment]
@sidsaxena0 THE SEARCH EXISTS FOR A REASON
