### ISSUE TITLE
[BUG] InvalidDateTime with 12H, Chrome 110 issue with ts-luxon v3.x

### ISSUE THREAD

**Issue by chintan121217** [tonysamperi/ngx-mat-timepicker#56]
**Describe the bug**
Getting  Cannot parse time - NaN on Chrome with Angular 13 

**To Reproduce**
Getting  Cannot parse time - NaN on Chrome with Angular 13 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/52502936/219095634-faf064cf-0dfa-47d9-8ab1-4562af8f0dff.png)
![image](https://user-images.githubusercontent.com/52502936/219097184-0a7f137e-ad22-421c-940e-7ce6414735cf.png)

**Desktop (if execution):**
 - OS: Windows 11
 - Browser Chrome

** Versions
 - ngx-mat-timepicker version : 13.2.6
 - @angular/core version : v13
 - @angular/material version: v13
 - typescript version : 4.6.2

**Additional context (optional)**
It's working in firefox only causing issue in chrome

**Comment by tonysamperi** [comment]
I would like to know why you use Angular 12 with core 13, but since it's not related...

**Comment by chintan121217** [comment]
> I would like to know why you use Angular 12 with core 13, but since it's not related...
> 
> Related to #53 and #51

My bad... it's 13 only..

**Comment by tonysamperi** [comment]
Fixed in v 13.2.7
