### ISSUE TITLE
[BUG] - wrong appearance

### ISSUE THREAD

**Issue by GlebStepenko** [tonysamperi/ngx-mat-timepicker#57]
**Describe the bug**
if you use ngx-mat-timepicker in lazy loading material dialog, it has wrong look.

**To Reproduce**

1. Go to https://github.com/GlebStepenko/ngx-timepicker-bug
2. ng serve
3. Click on Open lazy
4. Click on component

**Screenshots**
![2023-02-17_21-00-33](https://user-images.githubusercontent.com/2683578/219762241-6dfc0e0e-9100-435b-8f2a-edc1129dc744.gif)

**Desktop (if execution):**
 - OS: [Windows]

 - Browser [e.g. chrome]

** Versions
 - ngx-mat-timepicker version [e.g. 15.1.3]
 - @angular/core version [e.g. 15.1.0]
 - @angular/material version [e.g. 15.1.5]
 - typescript version [es. 4.9.4]

**Comment by tonysamperi** [comment]
Man you need to create a blitz, I can't download all the repos that people may create to test their bugs

**Comment by tonysamperi** [comment]
You can't use this libray without angular material, and I don't see it as dependency in your project.

**Comment by GlebStepenko** [comment]
ok, i created a blitz,

https://stackblitz.com/edit/angular-z6pmpk

i see the same wrong view

**Comment by tonysamperi** [comment]
@GlebStepenko it's your code. Let me know when you find the bug...

**Comment by GlebStepenko** [comment]
ok,

let's try differently

I don't want  import the NgxMatTimepickerModule module into my app's module, because i don't use this component on the start page and I don't want to add extra 25 kb to main.js

I think, transfer 
provide: MAT_FAB_DEFAULT_OPTIONS, useValue: {color: 'void'}
to NgxMatTimepickerFaceComponent  providers section   will solve the problem

**Comment by tonysamperi** [comment]
@GlebStepenko nope you don't need to do that. As I said it's in your code. You did 1 thing that doesn't make sense. 
If you solve that it works. I tried in your blitz of course...

**Comment by GlebStepenko** [comment]
what in my code has no sense ?

**Comment by tonysamperi** [comment]
If you think a little bit, I'm sure you can find out. 
I'm not giving the solution so that next time you won't do such mistakes

**Comment by GlebStepenko** [comment]
I totally don't understand how my code can affect the timepicker view

**Comment by tonysamperi** [comment]
@GlebStepenko go with this...much less than 25KB.

.mat-mdc-fab.mat-accent, .mat-mdc-mini-fab.mat-accent {
  --mdc-fab-container-color: transparent;
  --mat-mdc-button-persistent-ripple-color: transparent;
  box-shadow: none;
}

cheers

**Comment by tonysamperi** [comment]
@GlebStepenko that CSS needs to need global. You should disable encapsulation for your lazy component.

**Comment by tonysamperi** [comment]
@GlebStepenko that css needs to be global, you should disable encapsulation in your DialogLazyComponent
https://stackblitz.com/edit/angular-pnmmek
