### ISSUE TITLE
[BUG] - Picker displays two digits "3": 1,3,3,4,5,6,... Look at the Demo.

### ISSUE THREAD

**Issue by avsol** [tonysamperi/ngx-mat-timepicker#59]
**Describe the bug**
Picker displays two digits "3": 1,3,3,4,5,6,...

**To Reproduce**
Just look at your Demo: https://tonysamperi.github.io/ngx-mat-timepicker/

I have noticed this in the version 15.1.2, still present in 15.1.5

**Comment by tonysamperi** [comment]
Man are you serious? You think no one else would have noticed?

**Comment by tonysamperi** [comment]
Also there's a reason I made the bug template, you should fill in the required info...
This issue will be deleted in a few hour

**Comment by avsol** [comment]
This is interesting. I did see that yesterday, today it's gone. I can send you a screenshot if you are interested. Reproduced that in my local project too.
Can't imagine what that could be, definitely not a cache - I tried it in a private window.
Something related to timing or timezone
