### ISSUE TITLE
[BUG] - When switch go or back to date by an external fuction ngx-mat-datetime-picker doesn't update

### ISSUE THREAD

**Issue by adilorenzodema** [tonysamperi/ngx-mat-timepicker#6]
**Describe the bug**

I implemented this ngx-mat-datetime-picker:

![image](https://user-images.githubusercontent.com/77487424/111764192-3ed31600-88a3-11eb-9ef8-4f0dc4651cc0.png)

---------------------

It run regularly but when i change the date time by external function:  "switchDate(on: boolean)"
The time view change regularly:
![image](https://user-images.githubusercontent.com/77487424/111764783-e2bcc180-88a3-11eb-9eca-9c74123c63b6.png)

but not change the hours and minutes:
![image](https://user-images.githubusercontent.com/77487424/111762831-bd2eb880-88a1-11eb-81e9-96a3b7edd860.png)

Could you help me?

This is my TS:
![image](https://user-images.githubusercontent.com/77487424/111764582-a1c4ad00-88a3-11eb-8961-847976a88f60.png)
![image](https://user-images.githubusercontent.com/77487424/111764619-ad17d880-88a3-11eb-8c7f-28566d9476b4.png)

![image](https://user-images.githubusercontent.com/77487424/111764054-18ad7600-88a3-11eb-994f-e94ef4754a45.png)

**Desktop (if execution):**
 - OS: Windows
 - Browser chrome

** Versions
 - ngx-mat-timepicker version 5.x+
 - @angular/core version 11.1.2
 - @angular/material version 11.2.0
 - typescript version 4.1.3

**Comment by tonysamperi** [comment]
Mate, this is not my library!
