### ISSUE TITLE
[BUG] - Version mismatch of ts-luxon

### ISSUE THREAD

**Issue by Mairu** [tonysamperi/ngx-mat-timepicker#60]
**NOTE**

**Describe the bug**
With Version 5.1.3 the ts-luxon version in the main package.json has been updated to ^4.2.1 ( https://github.com/tonysamperi/ngx-mat-timepicker/blob/master/package.json#L52 )

But in the package.json of the package that will be used for the npm package ngx-mat-picker it is still ^3.0.1 ( https://github.com/tonysamperi/ngx-mat-timepicker/blob/master/projects/ngx-mat-timepicker/package.json#L27 ), is that on purpose?

**Additional context (optional)**
The problem is, that we use Angular 15 with your package @ngx-tonysamperi/ts-luxon-date-adapter which uses also ^4.0.1 as peerDependency.
When we want to use the libraries together this leads to errors because of different versions of ts-luxon and incompatibilities of the DateTime classes / instances.

**Comment by tonysamperi** [comment]
By the way, no. It's not on purpose. I need to see the history again, because I clearly remember that I wanted ts-luxon v4 with picker v15.
I'll have to fix this

**Comment by tonysamperi** [comment]
Fixed in v 15.1.7
