### ISSUE TITLE
If I keep hold the up and down array then hours and minutes are not changing it just change by 1 only when I leave click

### ISSUE THREAD

**Issue by ErVishalM** [tonysamperi/ngx-mat-timepicker#62]
Hi,

I was using this **ngx-mat-timepicker-field**, I found one unusual problem. If I keep hold the arrow svg then hours and minutes are not changing fast they are increasing only once when I leave the svg click. Please check below image for reference.
![image](https://user-images.githubusercontent.com/43669644/233556708-a852c6d9-cb8a-4cb9-a21e-d54877739eaf.png)

Expected - It should increase/decrease immediately till when I'm holding keys up/down svg. It should behave same as up and down keyboard arrow keys.
Kinda like [this](https://mdbootstrap.com/docs/standard/forms/timepicker/) (Try to check inline timepicker and when you hover on hour and minute then arrow keys will come and try to hold arrow keys.

Thank you.

**Comment by tonysamperi** [comment]
@ErVishalM absolutely not mate it's not unusual. It's how click events work in browser.

Cheers.
