### ISSUE TITLE
[BUG] - error TS2322: Type 'string' is not assignable to type 'number'.

### ISSUE THREAD

**Issue by autonomobil** [tonysamperi/ngx-mat-timepicker#63]
**Describe the bug**
When trying out the 24h example (https://tonysamperi.github.io/ngx-mat-timepicker/) with `format="24"` I get the error
```
- error TS2322: Type 'string' is not assignable to type 'number'
```

**To Reproduce**
https://angular-1rz8wv.stackblitz.io

**Expected behavior**
format should accept string instead of number

**Desktop (if execution):**
 - OS: Ubuntu 22.04
 - Browser: chrome

** Versions
 - ngx-mat-timepicker version 15.1.+
 - @angular/core version 15.2.8
 - @angular/material version 15.2.8

**Comment by tonysamperi** [comment]
Ok fixing the example!
