### ISSUE TITLE
[BUG] - Usage of ts-luxon instead of luxon

### ISSUE THREAD

**Issue by k3nsei** [tonysamperi/ngx-mat-timepicker#67]
**Describe the bug**
This library using `ts-luxon` as a dependency. Original `luxon` is more popular and is also most reliable library with a lot of trust. I don't want to include another copy of luxon clone into my bundle. If someone wants to have support of TypeScript? Just install `@types/luxon`.

P.S. @tonysamperi I know that `ts-luxon` is your library, but face reality. There is no need for it because existence of `@types/luxon`. Just stop bloating application bundles because of your ego.

P.S. 2 For people that don't want `ts-luxon` in their projects. You can use npm alias like shown below.

**package.json**

```json
{
  "overrides": {
    "ngx-mat-timepicker": {
      "@angular/animations": "^16.0.1",
      "@angular/cdk": "^16.0.1",
      "@angular/common": "^16.0.1",
      "@angular/compiler": "^16.0.1",
      "@angular/core": "^16.0.1",
      "@angular/forms": "^16.0.1",
      "@angular/material": "^16.0.1",
      "@angular/platform-browser": "^16.0.1",
      "ts-luxon": "npm:luxon@^3.3.0"
    }
  }
}
```

**tsconfig.json**

```json
{
  "paths": {
    "ts-luxon": ["node_modules/luxon/src/luxon.js"]
  }
}
```

**To Reproduce**
No need

**Expected behavior**
Use `luxon` and `@types/luxon` instead of `ts-luxon`.

**Screenshots**
No need

**Desktop (if execution):**
 - OS: All
 - Browser: All

** Versions
 - ngx-mat-timepicker version 15.1.7
 - @angular/core version 16.0.1
 - @angular/material version 16.0.1
 - typescript version 5.0.4

**Additional context (optional)**
No need

**Comment by k3nsei** [comment]
As an alternative please allow user to have their own implementation like Angular Material is doing with Date Adapters https://material.angular.io/components/datepicker/overview#choosing-a-date-implementation-and-date-format-settings

**Comment by tonysamperi** [comment]
mmm no.
