### ISSUE TITLE
🚨📢Unreliable mantainer/owner

### ISSUE THREAD

**Issue by k3nsei** [tonysamperi/ngx-mat-timepicker#68]
Unfortunately, but I have to conclude that mantainer @tonysamperi is an ignorant and untrustworthy person. He regularly deletes issues or closes them with comment blocking. This behaviour makes this dependency unsafe to use in your application. It is not possible to have a discussion with or contact the author.

I and company that I work with will drop usage of that library and fork it. Really it's not worth to rely on that person.

**Comment by tonysamperi** [comment]
@k3nsei I simply don't deal with morons...
