### ISSUE TITLE
Timepicker dialog auto-focus on '00'/'12' upon initialization

### ISSUE THREAD

**Issue by kjteh** [tonysamperi/ngx-mat-timepicker#7]
**Describe the bug**
The timepicker dialog will always auto focus on the '00'/'12' button after it has been opened. 

**To Reproduce**
Just open the any ngx-mat-timepicker

**Expected behavior**
Should not focus on any button

**Screenshots**
![Capture](https://user-images.githubusercontent.com/56550921/114152955-6ae93080-9951-11eb-88ec-7f3406fa56c7.PNG)
(The focus shadow at '00')

** Versions
 - ngx-mat-timepicker version [e.g. 9.0.0]
 - @angular/core version [e.g. 10.2.3]
 - @angular/material version [e.g. 10.2.7]
 - typescript version [es. 3.9.2]

**Additional context (optional)**
I suspect it is due to the `cdkTrapFocus` and `cdkTrapFocusAutoCapture` in the `ngx-mat-timepicker-dialog.component.html`. Removing it will solve the issue.

**Comment by tonysamperi** [comment]
Fixed in v 11.0.3! 🎉
