### ISSUE TITLE
[BUG] - Minute increase/decrease generating incorrect time when used with 24 hour format with no default value

### ISSUE THREAD

**Issue by mayankk245** [tonysamperi/ngx-mat-timepicker#71]
**Describe the bug**
Issue is with "ngx-mat-timepicker-field" component when using for 24 hour format with no default value. 
In **24 hour format** with no default value when user increase/decrease the minute. Time is getting generated as **12:01 or 12:59**. Which should not be the case, time should be generated as 00:01 or 00:59.

Steps to reproduce the behaviour:
1. Clone the code
2. Run npm i --force
3. open the project in VS code or any other code editor
4. Open ngx-mat-timepicker-field.component.ts , path:   **projects -> ngx-mat-timepicker -> src -> lib -> components -> ngx-mat-timepicker-field -> ngx-mat-timepicker-field.component.ts**
5. Search for **_changeTime()** function definition.
6. Put a console.log inside **_changeTime()** on line 256(might be on different line for you)  for **time** or **this.timepickerTime** and save it. 
7. Open demo.component.html, path: **projects -> ngx-mat-timepicker-repo -> src -> app -> components -> demo -> demo.component.html**
8. Search for **format = 24**, and look for below code 
<ngx-mat-timepicker-field color="warn" [format]="24" [defaultTime]="'23:11'"></ngx-mat-timepicker-field>
9. Remove defaultTime attribute from above element or replace it with below code and save it.
<ngx-mat-timepicker-field color="warn" [format]="24"></ngx-mat-timepicker-field>
11. Do ng serve. 
12. open http://localhost:4200/
13. Open console of the web browser and look for **ngx-mat-timepicker-field** section on the page.
14. Under format = 24 of ngx-mat-timepicker-field section. Increase or decrease the minute.
15. On console you will be able to see the issue with the time. It is not coming as expected.

**Expected behaviour**
For 24 hour format with no default value. When user is increase or decrease the minute the time should be generated as 00:01 or 00:59.

**Desktop (if execution):**
 - OS: Mac OS
 - Browser Chrome

** Versions**
 - ngx-mat-timepicker version 16.0..0
 - @angular/core version 14.0.0
 - @angular/material version 14.0.0
 - typescript version 5.0.0

**Comment by tonysamperi** [comment]
@mayankk245 man I don't know how to tell you...I did everything you say and there's no bug:

![ngx-mat-timepicker](https://github.com/tonysamperi/ngx-mat-timepicker/assets/5957244/21de9395-fe13-4389-be62-a2c4480a05c3)

**Comment by tonysamperi** [comment]
Ok now I get it. You mean that by default, when the hour is blank, you'll get `12:01` as value when you increase.
I think the best thing here is don't emit unless you've filled all the values.
I'l do some digging...

**Comment by tonysamperi** [comment]
Fixed in v 16.0.1. We don't emit unless both the values are filled!
