### ISSUE TITLE
Getting error while importing module

### ISSUE THREAD

**Issue by Akhil0046** [tonysamperi/ngx-mat-timepicker#78]
Error: node_modules/ngx-mat-timepicker/lib/directives/ngx-mat-timepicker.directive.d.ts:51:100 - error TS2344: Type '{ format: { alias: "format"; required: false; }; max: { alias: "max"; required: false; }; min: { alias: "min"; required: false; }; timepicker: { alias: "ngxMatTimepicker"; required: false; }; value: { alias: "value"; required: false; }; disableClick: { ...; }; disabled: { ...; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"format"' is incompatible with index signature.
    Type '{ alias: "format"; required: false; }' is not assignable to type 'string'.

51     static ɵdir: i0.ɵɵDirectiveDeclaration<NgxMatTimepickerDirective, "[ngxMatTimepicker]", never, { "format": { "alias": "format"; "required": false; }; "max": { "alias": "max"; "required": false; }; "min": { "alias": "min"; "required": false; }; "timepicker": { "alias": "ngxMatTimepicker"; "required": false; }; "value": { "alias": "value"; "required": false; }; "disableClick": { "alias": "disableClick"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; }, {}, never, never, false, never>;
                                                                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




** Angular Live Development Server is listening on localhost:1000, open your browser on http://localhost:1000/ **       


× Failed to compile.

**Comment by tonysamperi** [comment]
@Akhil0046 
Man, use the template and fill all the required info and create a blitz reproducing the issue.
But 99.9% there's something wrong with your code.
