### ISSUE TITLE
Incorrect installation guide at readme.md and demo

### ISSUE THREAD

**Issue by kjteh** [tonysamperi/ngx-mat-timepicker#8]
HI, thanks for maintaining this great repo all the time.

Found out that the install guide in readme.md is not updated:
`npm i --save luxon ngx-mat-timepicker` (should be ts-luxon)

as well in the demo webpage which showing: 
`npm i @popperjs/core`
`npm i ngx-popperjs`

Apart form this, any plan for making ts-luxon as part of the library dependency instead of as peer-dependency? It would be great just to do it like: 
`npm i --save ngx-mat-timepicker`

without to worry install a wrong version of ts-luxon 

Let me know if you need any helps from my side, tq

**Comment by tonysamperi** [comment]
Hi, I think you're right...
I'm about to publish an update for v10 and v11 (fixing appendToInput) so I'll add these! 

Thanks for reporting!

I'll also look into the other issue...v10 doesn't seem to have the focus issue, maybe they changed something in cdk v11
