### ISSUE TITLE
[BUG] - ESC input for timepicker seems not implemented

### ISSUE THREAD

**Issue by erikvorstenbosch** [tonysamperi/ngx-mat-timepicker#80]
**Describe the bug**
The documentation states to use `ESC` input for `NgxMatTimepickerComponent` for closing the timepicker by Esc-key.
Setting this input results in a compile error `error NG8002: Can't bind to 'ESC' since it isn't a known property of 'ngx-mat-timepicker'.`.
Current behaviour is that the timepicker does not close when using the Esc-key,

**Versions**
 - ngx-mat-timepicker version 16.0.3
 - @angular/core version 16.1.4
 - @angular/material version 16.2.0
 - typescript version 4.9.5

**Comment by tonysamperi** [comment]
Are you serious?
