### ISSUE TITLE
[BUG] - Missing dependency smp-core-utils

### ISSUE THREAD

**Issue by DevinloperNL** [tonysamperi/ngx-mat-timepicker#9]
**Describe the bug**
Missing dependency in latest version refuses to build the application.

**To Reproduce**
Run `ng build` without having the `smp-core-utils` dependency.

**Expected behavior**
The package should automatically install this dependency or not require it's installation.

**Screenshots**
![image](https://user-images.githubusercontent.com/22426652/114413121-fced7500-9bad-11eb-87e9-3be38a7df187.png)

**Desktop (if execution):**
 - OS: MacOS
 - Browser: Brave

** Versions
 - ngx-mat-timepicker version [10.0.2]
 - @angular/core version [10.2.4]
 - @angular/material version [10.2.7]
 - tslib version [2.0.0]

**Comment by tonysamperi** [comment]
Yup you're right, adding it to depencencies

**Comment by DevinloperNL** [comment]
If you could push a fix later today, you'd be a hero mate

**Comment by tonysamperi** [comment]
Yep. Already fixed v10, about to publish v 11!

**Comment by DevinloperNL** [comment]
You are a massive legend, my friend

**Comment by tonysamperi** [comment]
Done 🎉
