### ISSUE TITLE
[BUG] - Disabled buttons appearance

### ISSUE THREAD

**Issue by MaximBolduc** [tonysamperi/ngx-mat-timepicker#94]
**Describe the bug**
The visual is not the same if you select different hours. I had this bug in a project I use and found the same one in the online examples. 

In my own project I also get the same visual problem with the hours display
![image](https://github.com/tonysamperi/ngx-mat-timepicker/assets/22448486/683063f2-ed7f-450c-a929-61dc686bbf87)

In the example page of the project (https://tonysamperi.github.io/ngx-mat-timepicker/), the bug is present in the minutes section of the 12 hour format when you select "4 hours"
![image](https://github.com/tonysamperi/ngx-mat-timepicker/assets/22448486/ba48ab6c-ab48-4d6d-b748-500c081413e3)

**To Reproduce**
The error is present on the main example page as shown in the fallowing video.
https://github.com/tonysamperi/ngx-mat-timepicker/assets/22448486/39a563cb-c397-42ee-b3c2-335c78771ccc

**Expected behavior**
Same visual for all different hours and no as crowded in the minute page.
This image shows what I would expect
![image](https://github.com/tonysamperi/ngx-mat-timepicker/assets/22448486/5ec4b615-1a8e-46f7-9772-e25061d10e64)

**Screenshots**
![image](https://github.com/tonysamperi/ngx-mat-timepicker/assets/22448486/ba48ab6c-ab48-4d6d-b748-500c081413e3)
![image](https://github.com/tonysamperi/ngx-mat-timepicker/assets/22448486/683063f2-ed7f-450c-a929-61dc686bbf87)

**Desktop (if execution):**
- Brave
- Edge
- Probably others

** Versions
 - ngx-mat-timepicker version 17.0.0
 - @angular/core version 17.0.4
 - @angular/material version 17.0.1
 - typescript version 5.2.2

**Additional context (optional)**
Thank you for the amazing package. It has been a game changer for time input in my different projetcts.

**Comment by MaximBolduc** [comment]
I tried adding global style as suggested in #57 and the same behavior continues.

**Comment by achapman009** [comment]
In my apps case i had to be very specific in the overrides, this is what i did to get it looking properly...

I understand this snippet does not follow all best practices, but it is working for now. I hope it helps.

`.timepicker {
  > .timepicker__main-content > .timepicker__body {
    > * > ngx-mat-timepicker-12-hours-face > * > .clock-face > .clock-face__container > .clock-face__number {
      > .mdc-fab {
        box-shadow: none;
        
        &.mat-mdc-mini-fab.mat-primary {
          --mat-fab-foreground-color: #{rgb(133, 38, 62)};
        }
      }
    }

    > ngx-mat-timepicker-minutes-face > ngx-mat-timepicker-face > .clock-face {
      > .clock-face__container > .clock-face__number > .mdc-fab {
        &.mat-mdc-mini-fab {
          &.mdc-fab--mini {
            height: 0;
            width: 0;
          }

          &.mat-primary {
            --mat-fab-foreground-color: #{rgb(133, 38, 62)};
            height: 40px !important;
            width: 40px !important;
          }
        }

      }

      > .clock-face__clock-hand > .mdc-fab {
        top: -16px;
        left: calc(50% - 8px);
        height: 16px;
        width: 16px;
      }
    }
  }
}`

Results:
![image](https://github.com/tonysamperi/ngx-mat-timepicker/assets/20817730/0db3ae3c-48a5-4219-a20d-95fe13019c09)
![image](https://github.com/tonysamperi/ngx-mat-timepicker/assets/20817730/1b61b22b-123f-4eb8-add4-d1af3d30a56b)
![image](https://github.com/tonysamperi/ngx-mat-timepicker/assets/20817730/03f1145c-63b8-4c0f-9433-504ff575e97c)

**Comment by MaximBolduc** [comment]
Hi @achapman009,

I just tested your snippet and it fixes the minutes dialog, but not the hours one in my case. If I put my picker in 12h display everything work as intended with your suggested edit.  I'll search in that direction and find what I need to fix the 24h hour page. 

I'll leave the issue open since having it not consistent on the main example page is still an issue though.

Thanks for guiding me in the right direction and the quick reply!

**Comment by achapman009** [comment]
@MaximBolduc 

I took a glance, i think i got it figured out.. please look at line 24, i addeda  24 hour variant

![image](https://github.com/tonysamperi/ngx-mat-timepicker/assets/20817730/07d30077-c65f-4d7f-9c3e-b750bae26d9f)

**Comment by MaximBolduc** [comment]
> @MaximBolduc
> 
> I took a glance, i think i got it figured out.. please look at line 24, i added a 24 hour variant
> 
> ![image](https://private-user-images.githubusercontent.com/20817730/286035524-07d30077-c65f-4d7f-9c3e-b750bae26d9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMjMxOTcsIm5iZiI6MTcwMTEyMjg5NywicGF0aCI6Ii8yMDgxNzczMC8yODYwMzU1MjQtMDdkMzAwNzctYzY1Zi00ZDdmLTljM2UtYjc1MGJhZTI2ZDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDIyMDgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhYzdlYWE4NGY5YTU0YjY4YjRiMDZlYmY1OTAyOTQ1OTY0MDdjNzE1ODc1OThlZTY1ZmM0YzJhMGFlYmVjMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rcuk1C6xUs9XC_Udkb-Z5B1pAEXOC2w17hcD9Y1Jyc0)

We arrived basically at the same conclusion. I edited my last post a couple minutes ago to add the --inner field and the 24h variant. I'll update my styling for all my projects that use this library.

Thanks for taking the time to look at it a little more.

Have a nice day!

**Comment by tonysamperi** [comment]
Ok guys. Thanks, now I get the problem. Another guy raised the issue, but he didn't say anything on how to reproduce.
It's about the disabled buttons. When no minute is suitable (in the example the max hour is 4, so when you have 4 as hour, you can only have 0 as minute, so all the rest will be disabled).
Fixing this tomorrow morning.

Thanks

**Comment by tonysamperi** [comment]
Fixed in v 17.0.1
