### ISSUE TITLE
[BUG] - Timepicker hover section diverges when selecting time

### ISSUE THREAD

**Issue by vmuresanu** [tonysamperi/ngx-mat-timepicker#97]
1. Go to [Demo page](https://tonysamperi.github.io/ngx-mat-timepicker/)
2. Open Timepicker
3. Hover over some hour / minute
4. Select the hour / minute

**Expected behavior**
Selected hour has to be the same as the "preview / hover" hour.

**Actual behavior**
Selected hour diverges from the "preview / hover" hour.

**Screenshots**
![timepicker issue](https://github.com/tonysamperi/ngx-mat-timepicker/assets/26407402/4878f3f3-adda-450b-9fd5-9cf4009be3cf)

**Versions**
 - ngx-mat-timepicker version 17.0.2
 - @angular/core version 17.0.8
 - @angular/material version 17.0.7
 - typescript version 5.2.2

**Additional context (optional)**
The selected hour after click coincides with user's mouse. Which means that the problem is in the preview / hover projection.

**Comment by tonysamperi** [comment]
You're welcome to create a PR if you think this can be managed.
That depends on how CSS and Javascript work differently so there's actually no good way of managing the situation.
But I think the hovering should be visible only for minutes which are actually printed (0-5-10-15 etc..).
I'll do this quick change.

**Comment by vmuresanu** [comment]
Sorry, but this is the issue from v17.0.0, because in v16.0.0 there was no hovering placeholder, thus no issue. The problem is not in the hour or minute hovering. The problem is in the hovering placeholder itself, specifically the fact that it is not aligned and doesn't correspond with the "clicked / selected" value. The UX is just not right and it reproduces on every placeholder in the demo section.

**Comment by tonysamperi** [comment]
I decided to align the behaviour to the old versions, therefore removing the ripple (cause the old css stopped working after the v17 update, but was actually there).

Solved in v17.0.3.

Cheers
