### ISSUE TITLE
[BUG] - ControlValueAccessor's writeValue does not update displayed time

### ISSUE THREAD

**Issue by burner-account** [tonysamperi/ngx-mat-timepicker#99]
**Describe the bug**
As shown via PR #98  updating a form value does not update the displayed time of ngx-mat-timepicker-field.

**To Reproduce**
Click on the "Update Time" button

** Versions
 - ngx-mat-timepicker version 17.0.1
 - @angular/core version 17.0.0
 - @angular/material version 17.0.0
 - typescript version ~5.2.2
 
(project package.json)

**Comment by tonysamperi** [comment]
@burner-account 

1. Don't create random PR's
2. Don't describe a bug saying "as shown in the PR", if you want to report a bug, then you create an issue and link a Blitz reproducing the issue

Next time your issue will just get deleted.

Thanks

**Comment by burner-account** [comment]
Sry, did not want to bother you.
